### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Schlegen** [Szybet/kobo-screen-mirror#1]
Hello Szybet,

Thank so much you for your work. I think that this is very interesting and I am willing to use it in order to be able to share the screen of my Kobo elipsa during meetings. 

I am pretty new to rust, would this be possible to explain a bit more how to run it ?

Thanks in advance,
Nicolas

**Comment by Szybet** [comment]
Hello
Huh so this is a reason to run it

Well sad news:
1. It was never tested on a Kobo Elipsa
2. It was never tested with the default OS on kobo, only InkBox OS
3. It may even not work ( maybe the eink buffer is not readable, like on sunxi cpu's )
4. Depending what you want to use it for - for drawing it may be too slow ( without heavy modyfications )
5. I doubt that you have hacked your kobo elipsa for: ssh shell, fbink, fbgrab, usbnet yet - which are needed

rethink twice if you want to get into that, then after confirmation I will look for a bit of time to write a small guide for it.

**Comment by Schlegen** [comment]
Hello,

Thanks for your answer. Indeed, I am not planing to change my OS. 

Thanks,
Nicolas
